### ISSUE TITLE
Stage of Map Selection

### ISSUE THREAD

**Issue by dcloud102** [GkevinOD/msl-bot#10]
How do I change what stage of a map?  I updated my mirage ruins map, but it could not find the EXP Bonus stage.  Could it be set to Gold Bonus stage?

**Comment by Majinek** [comment]
It's set to pick first stage it can so if you unlocked 1-4 and game is showing 2-4 it will pick 2 if 1-5 then game shows 3-5 so bot is picking first stage it can.

**Comment by dcloud102** [comment]
That's the thing.  I unlocked mirage ruins all stages.  So, it shows a partial of the stage and it's clicking the gap between the stages.

**Comment by Majinek** [comment]
It should click stage energy picture

**Comment by Majinek** [comment]
Try to make new misc-stage-energy.bmp in images/misc folder it should help with problem if not try version from dev branch. Dev branch has new scripts only golems seems to have error for me idk why

**Comment by dcloud102** [comment]
Thanks, I'll give it a shot and see.

**Comment by GkevinOD** [comment]
Thing about the stage selection is that I currently have no way of scrolling up to the gold stage. There is a way if the real mouse does the action, but there is no control drag that I can find.

**Comment by Majinek** [comment]
I think it may be idea to check stages like .bmp files with imagesearch and if it is visible then it can click on this stage but not 100% it can be done

**Comment by dcloud102** [comment]
@GkevinOD I don't know if this post help, https://autohotkey.com/board/topic/40638-controlclick-dragging/ as it is not autoit.  I don't know much coding, so don't really understand the logic much.

**Comment by GkevinOD** [comment]
I'll be checking it out. I might be able to port it to autoit, but it's not a guarantee.

**Comment by zeromike** [comment]
Hi, can I use the bot on the latest bluestack2? BlueStacks Rooted 0.10.7.5601 doesn't work on my computer, it will crash after running for a while, and I haven't found a solution for that.

**Comment by GkevinOD** [comment]
@zeromike It is probably possible to run on bluestacks2, but the images might not be optimized. Also there may be issues with capturing screen and controls.

Anyways, on this feature of scrolling up and down, this can be done with real mouse mode and I might add this feature for real mouse mode.
Regarding the code from autohotkey, the api may not be compatible with autoit so translating it can have some issues. I personally haven't tried, but it's currently not a priority.
