### ISSUE TITLE
Sometimes thinks there isn't enough gems for a refill but it did refill.

### ISSUE THREAD

**Issue by mogulbgod** [GkevinOD/msl-bot#104]
Nox 6.0.0.0
Bot 3.9.4
Windows 7 Ultimate SP1
Description: Sometimes the bot thinks there isn't enough gems for an energy refill (but there is) after it had already refilled your energy and it automatically stops the script.

![msl-bot-not-enough-gem](https://user-images.githubusercontent.com/35021897/34541819-d7787fe2-f07d-11e7-82ae-50cda6a755c4.jpg)

**Comment by Arayalaa** [comment]
Hmm had none of these problems win10 also you probably want to show exact win version, just 7 doesnt really help.

**Comment by mogulbgod** [comment]
Added the extra information as suggested by Cyinthia.

**Comment by mogulbgod** [comment]
The problem still persists in 3.10.4 although not as often.
