### ISSUE TITLE
Line 28441 - Variable used without being declared

### ISSUE THREAD

**Issue by User-1980** [GkevinOD/msl-bot#105]
![image](https://user-images.githubusercontent.com/35158038/34635997-23698fb0-f27f-11e7-9582-0ec70d959452.png)

I was using the bot normally till this last update (3.10.0.0). Now it won't open anymore. Is it a problem in my computer, or something that need fixing? =/

**Comment by Arayalaa** [comment]
Had the same issue, but the error was with line 30839
Winver: 1709 OS build 16299.125
Nox: 5.0.0.1

EDIT: solved for me with 3.10.1
