### ISSUE TITLE
Filter doesn't filter properly

### ISSUE THREAD

**Issue by Arayalaa** [GkevinOD/msl-bot#110]
I disabled flat stats in general but it for some reason keeps picking them up. Have the settings for all % ones and 6* only with 3+ substats.

Bot ver 3.10.4
Win Ver: 1709 16299.125
Script: _Filter

**Comment by gquito** [comment]
Flat gems can appear due to titan rewards most of the time, but if the bot is mistaken then it should have logged it. If you can find the log in /profiles/USER/log to confirm this issue then I will investigate.

**Comment by Arayalaa** [comment]
does the current bot still work for golems?
