### ISSUE TITLE
Autos rather then catching while farming. (Farm gem mode) 

### ISSUE THREAD

**Issue by ghost** [GkevinOD/msl-bot#111]
Nox Ver. 5.0.0.0
Bot app Ver: 3.10.4
Script used: "Farm gem"

Hey there, I'm not exactly sure why this happened as I had not made any changes while it was farming golem, but halfway through the day, the bot has lost the ability to "slime". Rather then proceeding to catch the slime as it previously did, it gets stuck on "turning auto off" as it repeatedly spams the auto button. So it clears waves without catching a single slime. Yes the final round feature is still deactivated. It has also been having trouble when it comes to refilling energy via astrogems as it would just sit on the refill screen.

![untitled](https://user-images.githubusercontent.com/35818520/35414250-d4ccd038-0219-11e8-97af-9a3928e8a059.png)

**Comment by Arayalaa** [comment]
can confirm update broke it 
Winver: 1709 16299.192

**Comment by ReinaldStone** [comment]
Kevin is aware about it. Just be a little patients. I know you are trying
ti help telling where the bugs are. But consider that he also uses the bot.
Em 25/01/2018 19:51, "FAzure1" <notifications@github.com> escreveu:

**Comment by Arayalaa** [comment]
I'm just identifying windows versions that he did not include to either narrow it down or add some needed context

**Comment by ykson1102** [comment]
Guess the last msl update(2018.1.25) tried preventing several kinds of  auto bots. The bot program does not fill gems nor catch astromons automatically for now.
