### ISSUE TITLE
Auto Battle anos Catch Astromons Don't Work

### ISSUE THREAD

**Issue by OakVini** [GkevinOD/msl-bot#112]
All work.
Quests, pick nezz and etc..
But Catch Astromons and auto Battle don't work, It simply don't click for auto Battle or Catch Astromons.
When appear a astromon rare, legendary, exotic or super the bot stop and don't Catch.

**Comment by lebayinhere** [comment]
yeah me too

**Comment by Arayalaa** [comment]
already reported issue no current fix

**Comment by ykson1102** [comment]
Fixed and Updated. Love you Kevin♡.♡ Thank you so~~~~~ much!
