### ISSUE TITLE
Farm rare script

### ISSUE THREAD

**Issue by Majinek** [GkevinOD/msl-bot#12]
Hello @GkevinOD  it seems that bot stops working when Guardian Dungeon is discovered. First I thought i just need to replace image but couldn't find it in folders. Tried to debug and location is not detected then.
![image](https://cloud.githubusercontent.com/assets/25628438/23440739/4771c694-fe1e-11e6-8dcb-57bb954258b0.png)

**Comment by GkevinOD** [comment]
Usually the bot would try to click off of this screen. I'll add a way for the bot to always skip this screen.

**Comment by GkevinOD** [comment]
I attempted to fix the problem, can't confirm yet though. I will close this issue when it is confirmed that the issue is fixed.
