### ISSUE TITLE
Golem Auto Issue

### ISSUE THREAD

**Issue by Skiltvakten** [GkevinOD/msl-bot#121]
when the game crashes or has to reboot while farming golems the bot is able to navigate back to the dungeon but "forgets" to turn auto battle on.  it idles on the first wave.

**Comment by jihunhan** [comment]
In the Golem Dungeon, auto is off and is always stopped.

**Comment by KingSuperJam** [comment]
In golmes it never enables auto,  so if it gets stuck and reloads it'll go back to golems but  will just sit there on wave 1
