### ISSUE TITLE
Farming rare issue help!

### ISSUE THREAD

**Issue by BoxMSL** [GkevinOD/msl-bot#124]
I usually use 'Farm Rare', but this does not automatically sell Gems.

Since 'Farm Rare' is not applied to the _filter, it does not work even though it is set to 1,2,3,4 in 'Gems To Sell' in 'Farm Rare'

Please tell me how to solve this problem.

Thank you for always. :) 🥇

**Comment by gquito** [comment]
The Farm Rare script, unlike the Farm Golem script, will sell the gems once the inventory is full. The script should navigate to the gem inventory through your airship and sell it in bulk.
