### ISSUE TITLE
_CaptureRegion Is Not Working Anymore?

### ISSUE THREAD

**Issue by dcloud102** [GkevinOD/msl-bot#16]
I tried typing in _CaptureRegion("test.bmp",421,65,400,70) and it did not produce an image in the root directory.

**Comment by GkevinOD** [comment]
The points that you entered is invalid. The format is Left,Top,Right,Bottom

So try starting from the top-left of the rectangle as the first two integers then the bottom-right

**Comment by GkevinOD** [comment]
If that does not work, I will see what changed in that function because I don't remember changing anything from 1.5 -> 1.6

**Comment by dcloud102** [comment]
Yeah, that was just some random points that I threw out.  I just tested it again and it works.  The only difference from what I did before is I don't have the Find Image enable.  Thank you for keeping up with all these open items.
