### ISSUE TITLE
Farm Astromon Script

### ISSUE THREAD

**Issue by dcloud102** [GkevinOD/msl-bot#18]
Question - Is there a way to have farm astromon script catch legendary, exotic, super rare, rare, and variant while farming 1 star slime?  Or should I just use Farm Rare script and add "catch-one-star"?

**Comment by GkevinOD** [comment]
There is an option to catch-rares while farming 1 star astromons

**Comment by GkevinOD** [comment]
Catches all rares that you listed. The image is just the non rare that you want to catch. Qhich would be the one star
