### ISSUE TITLE
Log Not Showing Gems Stats in Golem Script

### ISSUE THREAD

**Issue by dcloud102** [GkevinOD/msl-bot#20]
I don't know if it's by design or not, but there are no logs about what gems was found and sold.

![capture](https://cloud.githubusercontent.com/assets/24919677/23621411/44a14bb0-0260-11e7-93ea-99faf1aa227d.JPG)

**Comment by GkevinOD** [comment]
The config output-all-process is responsible for displaying information which are good to know or just spam of sort. I had mine set to 0 (disabled) therefore it does not log all of the unimportant process also making it default on the latest version. You can enable it in the Config tab.
