### ISSUE TITLE
network connectivity issue

### ISSUE THREAD

**Issue by 593394978** [GkevinOD/msl-bot#23]
when the nerwork connectivity was unstable， the msl bot was stop at this interface.
I wait it about 10 min, It can not continue the next step. please fix this issue.
And thank big big big bro~~~~!
![stop](https://cloud.githubusercontent.com/assets/26210421/23793686/7d9e2b76-05c7-11e7-8148-33995b91b55e.jpg)
![network](https://cloud.githubusercontent.com/assets/26210421/23793683/776e0a14-05c7-11e7-8ff2-1e6287d3da14.jpg)

**Comment by Majinek** [comment]
Change picture with new one it will fix a problem

10.03.2017 12:33 PM "593394978" <notifications@github.com> napisał(a):

**Comment by 593394978** [comment]
@Majinek bro, could u teach me ?
I can't find this issue picture.  Orz```

**Comment by 593394978** [comment]
@Majinek
I try it, but it is no work.And i replace the "location-lost-connection.bmp".
![try](https://cloud.githubusercontent.com/assets/26210421/23801698/0c816cd0-05ec-11e7-903e-4136dba02d02.jpg)

**Comment by Majinek** [comment]
If You changed restart bot and wait if error persist sometimes it take time
for bot to check if there is connection issue

10.03.2017 16:51 "593394978" <notifications@github.com> napisał(a):

**Comment by Majinek** [comment]
Can't help now I am in work

10.03.2017 17:04 "Rafał Waśko" <majinek691@gmail.com> napisał(a):

**Comment by 593394978** [comment]
@Majinek can u share You MSL BOT?? please

**Comment by dcloud102** [comment]
@593394978 it all depends on your screen for optimization.  We all download the same bot, but some images are dependent your machine.  Have you replace any images?  Make sure you use the debug tab and click location to see if it is recognized where your location is.  If it is unknown, then you would need to update the image in \msl-bot-master\core\images\location, which is location-lost-connection.bmp.  Provide us a screenshot of that debug tab with location check box enable.

**Comment by GkevinOD** [comment]
@593394978 The line of code that you entered in Test Code: is not valid so it did not replace the image. When the lost-connection location shows up again try this: _CaptureRegion("core/images/location-lost-connection.bmp", 400, 310, 450, 312)

**Comment by GkevinOD** [comment]
I updated the _CaptureRegion() function so that you can create an image with just 2 points arranged in any order. So the points does not have to be top-left and bottom-right can be reversed; it will create the same image. 

I plan to create easier ways to optimize the locations and images within the bot in the future!

**Comment by 593394978** [comment]
@GkevinOD Thank very much!!

**Comment by 593394978** [comment]
@dcloud102 I try many time replace image, but has been prompted unknown.
why I m so bad luck.
@GkevinOD Can you provide a video tutorial or gif please(Optimizing the image recognition for the bot)?
Maybe my request is a bit too much.
I don't understand.why try many time,  it still can not work.
I follow the instructions step by step operation， but still not understand.

**Comment by GkevinOD** [comment]
I will have a system in the next major version that allows you to optimize locations with one click of a button. But here I made a GIF example of how to optimize a location: 

![output_tzgumz](https://cloud.githubusercontent.com/assets/5211248/23820643/3b655d8c-05d2-11e7-99c9-158fff2fe400.gif)

**Comment by 593394978** [comment]
let me try it```O(∩_∩)O
