### ISSUE TITLE
gems full can not sell

### ISSUE THREAD

**Issue by 593394978** [GkevinOD/msl-bot#24]
when gems were full.MSL BOT can not sell. it just open the gems view.And continue the battle.
![gemss](https://cloud.githubusercontent.com/assets/26210421/23798836/453948fa-05e1-11e7-85b1-3dc10cae6d12.jpg)
![gems](https://cloud.githubusercontent.com/assets/26210421/23798833/4110816c-05e1-11e7-9efa-e107e33bc26c.jpg

**Comment by GkevinOD** [comment]
The core/images/manage/manage-three-star.bmp needs to be replaced. I haven't gotten around to replacing the ones in the commits because I do not have three star gems.

**Comment by 593394978** [comment]
@GkevinOD Tks
