### ISSUE TITLE
Question Location-Pause

### ISSUE THREAD

**Issue by dcloud102** [GkevinOD/msl-bot#26]
What image do you take to replace location-pause?  Mine is not recognized so it would not go into catch-mode when a rare is found.

**Comment by GkevinOD** [comment]
@dcloud102 The only script that uses location-pause is Farm Astromon which is usually for farming slime, and occasional rares. The location-pause image is a small section of the settings icon when in pause, the continue button can be used as location as well.

**Comment by dcloud102** [comment]
Oh, I see.  So, what image do I have to take to get the bot to recognize that there are rare and super rare that appears in Farm Rare mode?

**Comment by GkevinOD** [comment]
It should be in the images/battle folder. There are only one of it's kind with the exception of the legendary. But to add to the battle-... images, you need to add to the global variable $imagesRareAstromon within the /core/global.au3. I will probably change this and make it so it automatically detects new images.

**Comment by GkevinOD** [comment]
Also because the icons to move about, it will take at most a minute to detect the image. Having more images will definitely be safer and faster.

**Comment by dcloud102** [comment]
Thanks.  So, do you just capture the image of static "rare, exotic, legendary, etc" and not the first image where it says "rare found" or something like that correct?

**Comment by GkevinOD** [comment]
Yes after that little rare found animation, you should take the images. Basically when you can see the game interface.

**Comment by dcloud102** [comment]
Thanks, I understand now.  BTW, there is an issue with mirage ruins.

[00:02:11] Going into battle...
[00:02:16] Locating map stage.
[00:02:20] Entering Mirage Ruins on Extreme.
[00:02:56] Error: Could not enter map stage.

After it changes to extreme, it cannot enter the stage.  Is it because of the misc-energy image?

**Comment by GkevinOD** [comment]
Most likely. I haven't the time to test all maps so this issue might arise.

**Comment by dcloud102** [comment]
Cool, thanks.  I'll close this topic then.
