### ISSUE TITLE
msl-bot 1.7.9 

### ISSUE THREAD

**Issue by Majinek** [GkevinOD/msl-bot#27]
It seems that bot can't give up after defeat it stucks on defeat screen even after changing picture of location-defeat.bmp and location-battle-pause.bmp
+ It does not reconginze guardian dungeon if there is only one of it if 2+ it's doing only second one and third etc. only skips first one
+ Spotted today thought it was PC freeze it was bot that stuck in farm rare script it hangs on victory screen and don't click anything if i remember correctly it happens after 50+ run and if i try to stop bot it doesn't respond in any way, need to force exit it.

**Comment by dcloud102** [comment]
I think another bug is that when it goes back to the village with gethourly(), sometimes it stay stuck at the quit game screen because too many "ESC" is sent? or coming back to village and event notification pops up.

![img_0111](https://cloud.githubusercontent.com/assets/24919677/23920413/8b08b3b8-08c8-11e7-8e3d-cf77b4b1ecb9.PNG)

**Comment by GkevinOD** [comment]
I'll be fixing this soon and making a failsafe condition. I deleted the picture you send dclouf because it had your username.

**Comment by dcloud102** [comment]
Awesome.  Thank you!!!!

**Comment by GkevinOD** [comment]
@Majinek In v1.8.x I've added easier ways to replace a location without having to find the actual points. The new readme.md explains how to use it. Regarding the guardian dungeons, you may need to replace the energy image so it can do all of the dungeons. For the bot becoming stuck, I'm not too sure what the issue on that one is so you may need to tell me how often it happens and what you think the problem may be.

@dcloud102 If you can, provide more detail of what actions take place when it gets stuck. The bot, in theory, should be able to get out those situations by itself. I don't always trigger these situations therefore it's hard to fix the problem without actually replicating it on my end.

**Comment by dcloud102** [comment]
@GkevinOD For me, bot is stuck at midnight central time.  When gethourly() is called, it goes back to the village and has all these notification pop up.  Such as new new day, contract quest, etc...  Perhaps I don't have the images optimized?

I also have the same problem as Majinek on being stuck at defeat screen in golem.  I have not done extensive testing on replacing images.  I'm guessing it would be the location-battle-defeat.bmp and battle-give-up.bmp?

**Comment by GkevinOD** [comment]
I may have to fix the defeat algorithm. I haven't lost so I just assumed it worked. It might be the defeat image, try using the new debug tool to add the location.

**Comment by dcloud102** [comment]
Will give all these a shot and report it back to you.

**Comment by dcloud102** [comment]
I tested 1.8.0 and added the location-defeat2.bmp with the new debug feature.  I also had to change the battle-give-up.bmp image and it is working for golem defeated.  The new image capture debug works.  Question on it though, how come it just doesn't replace the image if it exist?  Isn't that the reason why you are replacing the image?

I have not encounter the going back to village error yet.  As I have not run the bot at the midnight mark.  Will see tonight.

**Comment by GkevinOD** [comment]
Sometimes the image may have two variations, so one image might work for a location but may not work again for the same location in the future. Although it does slow down the speed of checking the location, it is not significant enough for you to notice ( probably less than 1/2 a second ).

Also I manage to reproduce the situation during midnight. I'm not too certain on why it doesnit fix by itself, but I might be able to fix it soon.

**Comment by Majinek** [comment]
New version works like charm thanks for the update :)

18.03.2017 14:16 "Kevin Quito" <notifications@github.com> napisał(a):

**Comment by GkevinOD** [comment]
@dcloud102 I think I found the problem with the bot getting stuck at midnight. When the event stuff shows up, and I think those things reset at midnight, the bot may get stuck in ESC window. There is a condition in the script that checks if location is 'unknown' and just clicks (mostly for when guardian dungeon shows up) so it does an infinite loop there. I've added a check for location-esc now and it should be able to work. Need more testing though.

**Comment by 593394978** [comment]
how can i get 1.8 version?

**Comment by GkevinOD** [comment]
@593394978 There are branches that contain the older version or the newest version. The master branch is usually for the most stable up-to-date version. 
![image](https://cloud.githubusercontent.com/assets/5211248/24088401/0f2489fc-0ce7-11e7-837b-d5530f7b1569.png)

**Comment by 593394978** [comment]
thanks for the update

**Comment by GkevinOD** [comment]
It still gets stuck at midnight, I have no clue why. I don't stay up late enough to see it happen. I might stay up to see what actually happens.

**Comment by dcloud102** [comment]
It is the contract quest.  Also, golem is still stuck at quest completed. It collect all the quests but doesn't navigate out of it.

**Comment by GkevinOD** [comment]
I've taken into account the contract quest, but I guess it didn't work. Also 1.8.5 should fix the problem with the golem. It also fixes a problem with misidentifying the missed/caught astromon in catch.au3 function.

**Comment by GkevinOD** [comment]
I'll be seeing personally what is happening during midnight and hopefully be fixing this issue within a few hours. If not, I will try again tomorrow.

**Comment by 593394978** [comment]
i test it all night , but can't not see catch the s' rare and legendary(maybe not meet it, lol).

**Comment by GkevinOD** [comment]
Yes I notice that problem too. The new version should be able to tell whether the astromon has been caught or missed. I will work adding more space in the data list because it runs out of space after around 10 astromon caught.
