### ISSUE TITLE
using bot with another emulator 

### ISSUE THREAD

**Issue by expiredyogurt** [GkevinOD/msl-bot#31]
how would i change the setting to use this script with another emulator? (nox emu)

I can't install bluestack on my pc due to path format error and there isn't a fix I can find online so I'm thinking about using nox as it works on my pc.

**Comment by GkevinOD** [comment]
I will create a tutorial on how to use other emulators such as nox (I will use nox as an example). The only thing about this is that background mode may not work with nox.

Ultimately, I will add support for other emulators on the scripts in a future update.

**Comment by expiredyogurt** [comment]
thank you for the answer, will wit patiently for that. god speed

**Comment by GkevinOD** [comment]
At the fastest speed, i can probably have this available today. But expect a few days.

**Comment by GkevinOD** [comment]
@expiredyogurt Manage to get nox wokring. It is in branch v1.9. Join https://discord.gg/UQGRnwf if you have any issues or bugs so I can update for you faster.
