### ISSUE TITLE
sell gems issue

### ISSUE THREAD

**Issue by 593394978** [GkevinOD/msl-bot#33]
when the gems were full , it can't not jump to sell gems 
and it is always click the battle botton, i don't know how to fix it.
![issue](https://cloud.githubusercontent.com/assets/26210421/24318246/0be6fc0c-113d-11e7-970d-980d10d52084.jpg)
![gems issue](https://cloud.githubusercontent.com/assets/26210421/24318317/e9b74ed8-113d-11e7-9e7c-383a9c760d86.jpg)

.

**Comment by GkevinOD** [comment]
Do you still need help? There was an issue with 1.8.6 and its navigate function. I modified it in 1.8.7

**Comment by 593394978** [comment]
i just see the new vesion, so i close the issue, lol
