### ISSUE TITLE
buy energy issue

### ISSUE THREAD

**Issue by 593394978** [GkevinOD/msl-bot#34]
i don't know why...help!!
![energy](https://cloud.githubusercontent.com/assets/26210421/24321685/86618d76-118d-11e7-9c54-40e2b9d4b1f3.jpg)

**Comment by 593394978** [comment]
it can auto to stop the "Farm Rare", too  QAQ
![issue](https://cloud.githubusercontent.com/assets/26210421/24321884/9ef6b564-1192-11e7-9820-4a983ac7a64c.jpg)

**Comment by Majinek** [comment]
Just like in log You're out of gems and game sent you to buy more

25.03.2017 12:03 "593394978" <notifications@github.com> napisał(a):

**Comment by GkevinOD** [comment]
I apologize for the bug. It appears that the bot did not close the window when it refill the gems, therefore it kept refilling. I will add some code so it does not refill with all your gems.

**Comment by 593394978** [comment]
@GkevinOD it doesn't matter ,  i just report the issue.  lol

**Comment by GkevinOD** [comment]
It should only refill once and not all at the same time. I'm also not too sure why it stops when it does not enter map; it should be able to try again.

**Comment by 593394978** [comment]
when i go to bed before, i will test it again.
And find issue .
Thank you very much!!~
--------------------------------------------------------------------

I see you,  the 1st!!! lol~!!!
wonderful
![qq 20170325141927](https://cloud.githubusercontent.com/assets/26210421/24322115/40407b80-1198-11e7-87ce-194ead809aa3.jpg)

**Comment by GkevinOD** [comment]
Haha! Shh

**Comment by 593394978** [comment]
congratulations!!!!!!!!!!!!!!

**Comment by 593394978** [comment]
@GkevinOD sometime the farm golem mode can give up the batle(about at 4~8sec).
can u fix it!!!
this is big issue!! I don't know why 
I SEE THIS ISSUE ABOUT 5~8 TIMES!
