### ISSUE TITLE
Sell Gem Function Is Not Working

### ISSUE THREAD

**Issue by dcloud102** [GkevinOD/msl-bot#35]
During Farm Rare script, bot detect gem inventory is full and goes back to the village.  Then it goes into storage and recognized that it is in location-manage, but it doesn't click on the manage button to sell gem.  Is there a manage image that I need to recapture?  I updated the location-manage but that's not the same.  Is it a coordinate?

**Comment by 593394978** [comment]
please download V1.8.7

**Comment by dcloud102** [comment]
This is still a bug for me.  There is either not enough delay when it goes into inventory or it is not clicking "manage" in time before clicking the 1*, 2*, 3*, 4*, sell check box.  Instead, it was clicking the "skills" info button.  Then it says done selling.

**Comment by GkevinOD** [comment]
I can get this fixed by today. I've been busy. Make sure the "monsters" location is set. It's when there is the list of monsters

**Comment by dcloud102** [comment]
Thanks.  Didn't realize that there is such an image.  I see why it doesn't work now. You probably have your storage unlock and mine is not.  So my image still has a lock icon, where you don't.

**Comment by GkevinOD** [comment]
Yes that image was taken before the update so i may need to change it to something more stable.
