### ISSUE TITLE
alway give up at 4~6s

### ISSUE THREAD

**Issue by 593394978** [GkevinOD/msl-bot#36]
help!!!   stop for this!!
![1111](https://cloud.githubusercontent.com/assets/26210421/24339631/9510df04-12df-11e7-97b0-435dae76f341.jpg)

**Comment by dcloud102** [comment]
It's working for me.  You might have to optimize your images.  Go to debug when you are in battle.  I probably doesn't recognized that you are in battle.  So follow the readme for capturing images by using the debugging method.  Most likely, your location-battle.bmp needs to be updated.  It would be an image of the pause button.

**Comment by GkevinOD** [comment]
dcloud is right, it is most likely the battle location so you need that replaced

**Comment by 593394978** [comment]
OK, let me try it```
