### ISSUE TITLE
Just a little issue + fix

### ISSUE THREAD

**Issue by Majinek** [GkevinOD/msl-bot#4]
If someone have error when trying to get bot to go on extreme levels of story mode You need to replace a line in config.ini 
difficulty-restrictions=normal,hard,expert 
to
difficulty-restrictions=normal,hard,extreme

**Comment by dcloud102** [comment]
Thanks.  I was having that bug.

**Comment by GkevinOD** [comment]
Fixed in v1.3.3 and above. Sorry I make a lot of updates, it might be kind of annoying to download new version all the time! I still haven't released an official stable version, so all these reports of bugs are good for everyone.
