### ISSUE TITLE
Golem script - Stops on Autobattle

### ISSUE THREAD

**Issue by Adrasteja** [GkevinOD/msl-bot#40]
Golem script sometimes after completion clicks on Autobattle and then cannot close it.
It seems that it clicks the location for "Gem Sell confirmation" button (that is located in the same coordinates as autobattle) after the confirmation was dismissed, thus causing pop-up. 

![autob](https://cloud.githubusercontent.com/assets/26905972/24670077/6673d060-1975-11e7-97c5-37eba0072a14.png)

**Comment by dcloud102** [comment]
Is this the latest 1.9.2.5 (check About tab for version info).  If this is in Master, then it hasn't been updated.  Version 1.9.2.5 fixed this issue but has a few other bugs, such as, after a few runs, it doesn't click quick restart and just hang there.  Other includes going back to village hourly twice within the first 10 mins to get rewards from bushes.  These are all issues discussed in discord.

**Comment by Adrasteja** [comment]
You are right, I have v 1.9.2.3. Will try with new version.

**Comment by Adrasteja** [comment]
Yes, version 1.9.2.5 solved this. Thanks!
