### ISSUE TITLE
 Error: Could not find instance.

### ISSUE THREAD

**Issue by unkn0wx** [GkevinOD/msl-bot#44]
How to fix this i got " Error: Could not find instance." 
Using nox done optimal setting and turn off all setting in msl game

**Comment by GkevinOD** [comment]
Make sure you set the 'emulator-title' correctly. If you have some version like NoxPlayer 3.8.1.1 then the version 'emulator-title=NoxPlayer'

**Comment by unkn0wx** [comment]
Thank you its working now
