### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Majinek** [GkevinOD/msl-bot#6]
Got an error today with not recongnized rare catch(it was succesful though)and if I want to modify or rather add new bmp file i need to edit what files? global variables and put bmp into catch with smth like catch_rare_4.bmp???

![image](https://cloud.githubusercontent.com/assets/25628438/22976025/4906d4d0-f389-11e6-87c0-2f76aa887268.png)
![image](https://cloud.githubusercontent.com/assets/25628438/22976062/665448e2-f389-11e6-9493-976fe72cf121.png)

**Comment by GkevinOD** [comment]
There is a double check system for 1.3.5 and above. But if you do want to add the img file, you will have to trim the unrecognized img and follow the format in /core/images/catch/ folder.
