### ISSUE TITLE
Farm rare script keeps turning off auto refill chips

### ISSUE THREAD

**Issue by qooqle923** [GkevinOD/msl-bot#71]
As title. This happens after the update.

**Comment by zolcol** [comment]
I thought i was the only one

**Comment by qooqle923** [comment]
I think i know the reason. The bot click too fast during the map picking stage(my case gold stage) non stop while my pc loads too slow, and auto refill chips has the same image position as map picking.

**Comment by zolcol** [comment]
Change your laptop setting to maximum performance in battery settings..solved the problem for me

**Comment by qooqle923** [comment]
Im already in maximum performance but my pc is too old. I think slowing down the clicks during map picking stage will solve this issue.
