### ISSUE TITLE
Farming Gem or Catching 1 star astromon issue

### ISSUE THREAD

**Issue by NinjaKawasaki** [GkevinOD/msl-bot#73]
The bot could not see 1 star astromon after it automatically pause the auto attack and searching for 1 star astromon to catch. After it couldn't distinguish 1 star astromon, it turn the auto attack back again and attack all those astromon. 

Aprreciated for your works
Deviruchi

**Comment by NinjaKawasaki** [comment]
I fixed it, its up to Nox version that caused problem, i am currently using 3.7.1.0 it works well except, screen swiping that had problem, what kind of Nox are you guys using

Cheers
Deviruchi

**Comment by GkevinOD** [comment]
Using Nox version 5.0.0.1. As for the problem with swiping, it might be because of how you set up the key mapping. You can possibly fix this problem by redoing your key mapping. 

If you cannot fix it then describe the problem. For example, the swiping is either slow or not working at all.

**Comment by NinjaKawasaki** [comment]
thx you kevin appriciated your works
