### ISSUE TITLE
Guardian Dungeon

### ISSUE THREAD

**Issue by nicktyc** [GkevinOD/msl-bot#76]
Hello,

I'd like to enquire how come the script doesnt work for guardian dungeons despite setting it to farm and check them?

**Comment by Nowbob** [comment]
This was bugging me the past couple days too. The solution is to set "guardian-mode" to "2" if you want it to farm all guardian dungeons, and "1" if you only want it to farm the right-most dungeon (Seira in the current case). I believe the default is 1 and that was what was screwing me up.
