### ISSUE TITLE
[Bug] Stuck on Super Laboratory

### ISSUE THREAD

**Issue by xtherebellion** [GkevinOD/msl-bot#79]
Looks like the game gets stuck when collecting hourly sometimes, this occurs when it accidentally opens up Super Laboratory that is near one of the trees and doesn't exit this screen, thus getting stuck.

**Comment by vk479** [comment]
May I also add to this that it clicks the limited deal packages also by accident if this is not yet known.

**Comment by GkevinOD** [comment]
This bug will be fixed in the upcoming v3. You can already use v3 by downloading from the v3.0 branch, but the scripts is limited to Farm Golems. Updates will be made frequently to restore the previous existing scripts. Thank you for the input.
