### ISSUE TITLE
Refill using Astrogem

### ISSUE THREAD

**Issue by dcloud102** [GkevinOD/msl-bot#8]
Was wondering if there is a quick way for me to enable refill using astrogem with the farm script?

**Comment by GkevinOD** [comment]
I personally don't feel comfortable having a bot spend astrogems for me currently. When the bot becomes more stable then I can implement it later though.  Usually I just overfill my energy so I can farm overnight.

**Comment by GkevinOD** [comment]
I didn't quite read your question right. A quick way to refill your energy... Right now i did not implement a location to check if you've run out of energy so it would be tougher add one without understanding my code. For now there no quick way to do so, but ill be sure to keep in mind the idea of having a safe refill system.

**Comment by GkevinOD** [comment]
I've added it in v1.6+
