### ISSUE TITLE
Dev Branch

### ISSUE THREAD

**Issue by Majinek** [GkevinOD/msl-bot#9]
Don't know if dev branch is for testing too, but couldn't resist the urge to try it :) 
Farm slimes works like charm sometimes it stucks and sometimes not idk why
Farm golems couldn't test it don't have unlocked 7-10 stages anyway error I am getting when trying to go golem 4 is:
[14:29:57] ~~~Starting 'Farm Golem' script~~~
[14:30:27] Error (clickPoint): variable passed in is not an Array.
[14:30:30] Error (clickPoint): variable passed in is not an Array.
[14:30:32] Error (clickPoint): variable passed in is not an Array.
[14:30:35] Error (clickPoint): variable passed in is not an Array.
[14:30:56] ~~~Finished 'Farm Golem' script~~~

**Comment by GkevinOD** [comment]
I do not have b1-6 set up to navigate to that is why it does not work for you. I'm planning to add that feature today and I'll update you on here once that is finished.

As for the branches, I'll put the stable builds in master and the dev branch might be unstable or some features are not complete. Everyone is free to try it out though.

**Comment by Majinek** [comment]
I added map cords in global variables for 1-6 but I don't think that it was an issue for  Error (clickPoint): variable passed in is not an Array, maybe missed smth. Anyway i have old bot and quick restart script so it's cool :D

**Comment by GkevinOD** [comment]
I'll be adding these features in v1.6+.
