### ISSUE TITLE
Targeting Boss problem

### ISSUE THREAD

**Issue by ykson1102** [GkevinOD/msl-bot#91]
Description:
I was trying farming elements for dark super stones. So I set mode as 'farm rare', 'Sky Falls extreme', 'boss map', 'Target Boss enabled'. However, the targeting function does not work, and that turn fall into fail. I also experienced same thing in the 'Glacial Plains' map. Is it because of lack? Would it be solved if I change my graphic card with better one? Always thank you! 

Nox version. version 6.0.0.0
Bot app version. version 3.9.0
Script that you used. Farm Rare
Description of the problem.

**Comment by Arayalaa** [comment]
Just out of curiosity with your nox version, is that beta?

**Comment by ykson1102** [comment]
Nope, I guess it is not the beta version.
Other players in my clan also have the same problem.
My GPU is NDIVIA GeForce GT 730. CPU is i7-6700 @3.40GHz, RAM is 16GB.
Is the NOX setting is harsh to my computer?

![nox version capture](https://user-images.githubusercontent.com/33721840/33403580-469f7b90-d5a4-11e7-8859-714da242179d.JPG)
![nox version capture2](https://user-images.githubusercontent.com/33721840/33403596-5c0a923a-d5a4-11e7-9161-26de43299649.JPG)

**Comment by gquito** [comment]
The target boss feature was made with only golems in mind. The other bosses in story mode may not work because the boss astromon is too small and the script is not clicking in the correct position. 

I will attempt to fix this issue in the next few updates.

**Comment by ykson1102** [comment]
Okay, I see. Thank you so much!! ♥.♥
