### ISSUE TITLE
Gem farming evolution misclick

### ISSUE THREAD

**Issue by Arayalaa** [GkevinOD/msl-bot#92]
Whilst in evolution for the king slime it misclicks on the previous evolution and seems to miss tap. It doesnt exit evolution preview and then afterwards gets out and taps the skills for slime by accident and then goes to farm more slime, its a 50-50 whether it misses or not it would seem.

Nox version. Ex. version 5.0.0.1
Bot app version. Ex. version 3.9.0
Script that you used. Farm gem

**Comment by gquito** [comment]
v3.9.1 has a new algorithm for evolving. If this error still occurs, make another issue.
