### ISSUE TITLE
Collecting hourly goes into laboratory v3.9.1

### ISSUE THREAD

**Issue by Arayalaa** [GkevinOD/msl-bot#94]
When collecting it finishes collecting but for some reason clicks into the lab I wasn't there to see it. I just saw it ended up in the lab. It had not yet bought the items from the shop. The perspective was collecting from the right side of the ship in the direction of travel.

**Comment by gquito** [comment]
The most likely reason for this is that it is trying to click on Nezz. I have the script click on the positions where nezz might be; therefore, it might click on some UI in the game like the laboratory. There are no scripts to purchase items from the shady shop, but is a feature that will be made in the near future.

If the nezz clicking feature make the script unable to continue then make another issue.
