### ISSUE TITLE
"Error: Subscript used on non-accessible variable."

### ISSUE THREAD

**Issue by ykson1102** [GkevinOD/msl-bot#95]
Description:
 I set mode as 'Farm rare', 'Glacial Plane extreme', 'Stage 6'. Next error message was popped up and the nox screen was stopped at the moment trying to catch Variant astromon. 
![mslbot20171204_error](https://user-images.githubusercontent.com/33721840/33550527-9af95702-d931-11e7-841f-6a8b955ea7a4.JPG)

Nox version. version 6.0.0.0
Bot app version. version 3.9.1
Script that you used. Farm Rare - Glacial Plane - Stage 6

**Comment by gquito** [comment]
ImageSearch library requires the app to be run as x86. Either run the msl-bot.au3 as x86 by right clicking and selecting the option or running the executable.

**Comment by ykson1102** [comment]
Thank you so much! I guess the default option was  (Running with x64). Now I know how to run it correctly. 

Have a good day!
