### ISSUE TITLE
After noxplayer restarts

### ISSUE THREAD

**Issue by Arayalaa** [GkevinOD/msl-bot#98]
After the bot restarts the app it gets stuck after loading the ship because it presses back and opens up do you want to quit window and stops.

Bot Version: 3.9.3
Windows 10 version 1709
Nox version. Ex. version 5.0.0.1
Was running Farm Guardian script

EDIT: Appears to happen regardless of script you are running, and happens in 3.9.4 as well

**Comment by Cyinthia** [comment]
Still happens in 3.9.4 but less frequently
